plugins:
  - jekyll-remote-theme
  - jekyll-relative-links # converts links to markdown files to their html counterparts
relative_links:
  enabled: true
  collections: true
#
header_pages:
header_pages:
  - content/01-project-overview.md
  - content/02-project-outputs.md
  - content/03-participants.md
  - content/04-the-toolbox.md
  - content/05-bibliographies.md
  - content/06-the-laboratory.md
  - content/07-training.md
  - content/08-blog-posts.md
#
kramdown:
  # parse markdown inside block-level HTML tag
  parse_block_html: true
#  
hide_site_feed_link: true
#  skin: solarized
# 
# see https://github.com/jekyll/minima/blob/master/_config.yml for documentation
# theme: minima
remote_theme: "jekyll/minima@1e8a445"
# remote_theme: pages-themes/slate@v0.2.0
